before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: 5ft4KTtRkS1f07XJ9nzqtTVv+LOV3xHH2JD6N/NGyHUIL5qcRLocbefLHmXbEMZMN5lMXDNnJFxCBMN51ZK0qiynS0rfXtF+FaBrb0yP1JVRJCMwHmttoKMv2VbwL+asOGco85w3g+GOf9EIe4YpPxOIaweDaMZ8l6ECuhndMKy3Qeq1JPa8bbBrs6U3pS3PfoGTdJBuO0z4xcIg6vosEOggU0qQhNBz9ZGYCDTSVGhM2gxKuUtmkAki+wnyBzxg6s1ow2aBjloLG8pjMWV/nhMmMito1DH2eD5dDbzDYeACcf4ODMC1UZFfprClkLheWDaGw1uyV0Is1fl2ahH4r/jmCkBWY1M0a/zQD3i3NXqsuo24QqnzLbkMAqAyRCjV+fvF1H3CCxePAhwRp0mxVKUlTDCKp1rbmBynV9TiPqap9OWLmhJSBEJ9enOemf41h11DhYPpKGOFkGJrT8Spk6ptQco5Pc6pKQP7AFur1VDBqwiJGGVNyMVkmVHzFUI2ko3RVx1dGppCQzt4VInI4ZNy/ZsFHI8/HkQ3ZY8IwQ8LKf+svdIbv7zDIyMHuNx2zj5PPiEE/KCDeLtDxaBRSj/tnw5nYWys9XjwUsS0ZiMIpmU/D3MryyedDkwrU6w4iU1IpdCzYhnNMvXyKOj+/GHvgxr87M3xqJO+KDQEqeU= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
